### PR TITLE
stop using the expected nodes in teh UI and use the total node count …

### PR DESCRIPTION
**Pull request by jake-cross**
…to show how many nodes have been deployed to

## Fixed
Stop using the `expectedNodes` number which is not what we want to show in the nodes deployed section of the details of a deployment. Use the total number of nodes to show the total number of nodes.

### CODE REVIEW

**Comment by DavidIHunt** [comment]
Nodes.length is the number of nodes which have picked up the deployment and started the install. Where no nodes have yet done this (before load - possibly delayed by first puppet run for new machines) this value will be 0. I suggest changing to _.max(nodes.length, expectedNodes)

**Comment by jake-cross** [comment]
The whole thing is a bit messy. If `expectedNodes` is the value we want, there shouldn't be any reason to not just use `expectedNodes`. When the deployment _is_ complete, the value we would have previously shown on `expectedNodes` is jibberish and the user goes from a screen of 0/2 to 2/5 to 4/8 to 8/8 (complete). It's like a windows progress bar that says 99% complete in 2 seconds and estimates 2 days before complete. Switching between expected and nodes length will result in the same changing of numbers in the UI as just using nodes length so I'm not sure why we'd try to produce more accurate inaccuracies.

**Comment by DavidIHunt** [comment]
I'm not sure I agree.. Our deployments are really just continuous convergence on desired state. I think we want to help people understand and embrace that, rather than pretend a deployment is a fixed set of actions from the start. It makes sense in my mind that the desired state changes over time, and that the UI should reflect that. e.g.. When the service was first deployed we expected it to be installed on 2 nodes. Before that could happen, 2 additional nodes were created. We now expect the service to be installed on 4 nodes. It's just updating the state of play!

**Comment by jake-cross** [comment]
How does this differ to using the nodes length? If we can use expected nodes, I would assume we _know_ the number of nodes. Otherwise, isn't length that starts at zero depending on puppet etc going to start increasing and you're still seeing an updated state of play. Nodes length will show them that update with valid numbers as they increase... expected nodes is a guess. Let's just update a real figure and display that.

**Comment by DavidIHunt** [comment]
It's just to cater for the delay in nodes starting and updating consul (which can be significant if they're new nodes). nodes.length is what I think we want most of the time. I'm just trying to cater for new nodes which haven't had the CDA etc. installed yet. It's also to sync the understanding with the deployment monitor. The deployment monitor will wait for expectedNodes before completing. If it just used nodes.length, a lot of deployments would complete successfully before even the first node had got started. If we want to stick with nodes.length.. That's fine. I don't hate that idea. I just think it should be consistent.

**Comment by jake-cross** [comment]
On the consistency aspect, we most certainly agree. "I expect to install on this many nodes" - but that number just isn't correct. It sounds like it's just being used as a buffer to allow the Deployment Monitor to work properly and I don't like that method. When the expectedNodes is jibberish, and could be a constant of 1 and still provide the same value we're getting from it now, I just don't like it. I can understand from your explanations why it is used and why it is there, but I think it's messy and we could do something to improve this flow of deployments in the future so that we can say definitively "The completed deployment will be on X nodes" where X doesn't fluctuate.

**Pull request merged**
